#!/bin/bash
# Created by Mohit Joshi
# Updated by Parveez Baig

# Internal variables, please do not change
RANDOM=`date +%s%N | cut -b14-19`;
RANDOMD=$(echo $RANDOM$RANDOM$RANDOM | sed 's/..\(......\).*/\1/');
RESUME_MODE=0;REPEAT_MODE=0;WORKDIRACTIVE=0;ENGINE=InnoDB;
TRIAL=0;SCRIPT_PWD=$(cd `dirname $0` && pwd);
MYSQLD_START_TIMEOUT=60;PXC=0;PXC_START_TIMEOUT=60

function Help()
{
echo "usage: 1.[RESUME MODE] $BASH_SOURCE --incident-dir=<val> --resume-dir=<val> --step=<val>"
echo "       2.[REPEAT MODE] $BASH_SOURCE --incident-dir=<val> --resume-dir=<val> --step=<val> --repeat=<val>"
echo "       3.[GET DUMP AND SQL FILES MODE] $BASH_SOURCE --incident-dir=<val> --resume-dir=<val> --step=<val> --get-dump-and-sql-files --sql-files-dir=<val>"
echo "       4.[GET SINGLE THREADED PSTRESS SQL FILES MODE] $BASH_SOURCE --incident-dir=<val> --resume-dir=<val> --step=<val> --get-single-threaded-pstress-sql-files --sql-files-dir=<val>"
echo "  --incident-dir: The parent incident directory generated by pstress-run.sh"
echo "  --resume-dir  : The directory path where the replay runs will be saved"
echo "  --step        : The step from where the pstress runs will be resumed"
echo "  --repeat      : Repeat the step provided number of times"
echo "  --get-dump-and-sql-files : Get the dump of previous step and SQL files from the desired step"
echo "  --sql-files-dir : The directory path where the SQL files will be saved (default: $HOME/pstress_sql_files)"
echo "  --get-single-threaded-pstress-sql-files : Get only the pstress SQL files until the step from single threaded pstress run"
echo "  --keep-server-running : Keep the server running after getting the dump and SQL files, only works in combination with --get-dump-and-sql-files"
}

function parse_args() {
  local param value
  local positional_params=""
  while [[ $# -gt 0 ]]; do
      param=`echo $1 | awk -F= '{print $1}'`
      value=`echo $1 | awk -F= '{print $2}'`

      # possible positional parameter
      if [[ ! $param =~ ^--[^[[:space:]]]* ]]; then
        positional_params+="$1 "
        shift
        continue
      fi
      case $param in
        --help)
          Help
          exit
          ;;
        --incident-dir)
          INCIDENT_DIR=$value
          ;;
        --resume-dir)
          RESUME_DIR=$value
          RESUME_MODE=1
          ;;
        --repeat)
          REPEAT=$value
          REPEAT_MODE=1
          ;;
        --step)
          STEP=$value
          ;;
        --get-dump-and-sql-files)
          GET_DUMP_AND_SQL_FILES=1
          ;;
        --sql-files-dir)
          SQL_FILES_DIR=$value
          ;;
        --get-single-threaded-pstress-sql-files)
          GET_SINGLE_THREADED_PSTRESS_SQL_FILES=1
          ;;
        --keep-server-running)
          KEEP_SERVER_RUNNING=1
          ;;
        *)
          echo "ERROR: unknown parameter \"$param\""
          exit 1
          ;;
        esac
        shift
    done

}

# Output Function
function echoit(){
  if [ ${REPEAT_MODE} -eq 1 ]; then
    echo "[$(date +'%T')] [${TRIAL}.${COUNT}] $1"
  else
    echo "[$(date +'%T')] [${TRIAL}] $1"
  fi 
}

# Trap ctrl-c
trap ctrl-c SIGINT

function ctrl-c(){
  echoit "CTRL+C was pressed. Attempting to terminate running processes..."
  KILL_PIDS=`ps -ef | grep "${RANDOMD}" | grep -v "grep" | awk '{print $2}' | tr '\n' ' '`
  if [ "${KILL_PIDS}" != "" ]; then
    echoit "Terminating the following PID's: ${KILL_PIDS}"
    kill -9 ${KILL_PIDS} >/dev/null 2>&1
  fi
  echoit "Done. Terminating replay-test.sh with exit code 2..."
  exit 2
}

# Kill the server
function kill_server(){
  SIG=$1
  echoit "Killing the server with Signal $SIG";
  { kill -${SIG} ${MPID} && wait ${MPID}; } 2>/dev/null
}

# Start the server
function start_server() {
  PORT=$[50000 + ( $RANDOM % ( 9999 ) ) ]
  echoit "Starting mysqld server..."
  CMD="${BIN} ${MYSAFE} ${MYEXTRA} --basedir=${BASEDIR} --datadir=$DATADIR --tmpdir=$TEMPDIR \
--core-file --port=$PORT --pid_file=$PID_FILE --socket=$SOCKET ${KEYRING_PARAM}  \
--log-output=none --log-error-verbosity=3 --log-error=$ERROR"
  echoit "$CMD"
  $CMD > ${ERROR} 2>&1 &
  MPID="$!"

  echoit "Waiting for mysqld (pid: ${MPID}) to fully start..."
  for X in $(seq 0 ${MYSQLD_START_TIMEOUT}); do
    sleep 1
    if [ "$MPID" == "" ]; then echoit "Assert! $MPID empty. Terminating!"; exit 1; fi

# Check if mysqld is started successfully
    if ${BASEDIR}/bin/mysqladmin -uroot -S${SOCKET} ping > /dev/null 2>&1; then
      echoit "Server started ok. Client: `echo ${BIN} | sed 's|/mysqld|/mysql|'` -uroot -S${SOCKET}"
      break;
    fi
    if [ $X -eq ${MYSQLD_START_TIMEOUT} ]; then
      echoit "Server (PID: $MPID | Socket: $SOCKET) failed to start after ${MYSQLD_START_TIMEOUT} seconds. Will issue extra kill -9 to ensure it's gone"
      { kill -9 $MPID && wait $MPID; } 2>/dev/null
      exit 1
    fi
  done
}

# Start the PXC server
function start_pxc_server() {
  ${BASEDIR}/bin/mysqld --defaults-file=${CONFIG1} $STARTUP_OPTION $MYEXTRA --wsrep-new-cluster > ${ERR_FILE1} 2>&1 &
  pxc_startup_status ${SOCKET1} ${ERR_FILE1}
  ${BASEDIR}/bin/mysqld --defaults-file=${CONFIG2} $STARTUP_OPTION $MYEXTRA > ${ERR_FILE2} 2>&1 &
  pxc_startup_status ${SOCKET2} ${ERR_FILE2}
  ${BASEDIR}/bin/mysqld --defaults-file=${CONFIG3} $STARTUP_OPTION $MYEXTRA > ${ERR_FILE3} 2>&1 &
  pxc_startup_status ${SOCKET3} ${ERR_FILE3}

  echoit "Checking 3 node PXC Cluster startup..."
  for X in $(seq 0 10); do
    sleep 1
    CLUSTER_UP=0;
    if ${BASEDIR}/bin/mysqladmin -uroot -S${SOCKET1} ping > /dev/null 2>&1; then
      if [ `${BASEDIR}/bin/mysql -uroot -S${SOCKET1} -e"show global status like 'wsrep_cluster_size'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_cluster" | awk '{print $2}'` -eq 3 ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
      if [ `${BASEDIR}/bin/mysql -uroot -S${SOCKET2} -e"show global status like 'wsrep_cluster_size'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_cluster" | awk '{print $2}'` -eq 3 ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
      if [ `${BASEDIR}/bin/mysql -uroot -S${SOCKET3} -e"show global status like 'wsrep_cluster_size'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_cluster" | awk '{print $2}'` -eq 3 ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
      if [ "`${BASEDIR}/bin/mysql -uroot -S${SOCKET1} -e"show global status like 'wsrep_local_state_comment'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_local" | awk '{print $2}'`" == "Synced" ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
      if [ "`${BASEDIR}/bin/mysql -uroot -S${SOCKET2} -e"show global status like 'wsrep_local_state_comment'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_local" | awk '{print $2}'`" == "Synced" ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
      if [ "`${BASEDIR}/bin/mysql -uroot -S${SOCKET3} -e"show global status like 'wsrep_local_state_comment'" | sed 's/[| \t]\+/\t/g' | grep "wsrep_local" | awk '{print $2}'`" == "Synced" ]; then CLUSTER_UP=$[ ${CLUSTER_UP} + 1]; fi
    fi
      # If count reached 6 (there are 6 checks), then the Cluster is up & running and consistent in it's Cluster topology views (as seen by each node)
    if [ ${CLUSTER_UP} -eq 6 ]; then
      ISSTARTED=1
      echoit "3 Node PXC Cluster started ok. Clients:"
      echoit "Node #1: `echo ${BIN} | sed 's|/mysqld|/mysql|'` -uroot -S${SOCKET1}"
      echoit "Node #2: `echo ${BIN} | sed 's|/mysqld|/mysql|'` -uroot -S${SOCKET2}"
      echoit "Node #3: `echo ${BIN} | sed 's|/mysqld|/mysql|'` -uroot -S${SOCKET3}"
      break
    fi
  done
}

function get_dump_and_sql_files() {
  for file in ${INCIDENT_DIR}/${STEP}/default.node.tld_step_${STEP}*
  do
    ${SCRIPT_PWD}/pstress_log_to_sql_converter.sh --logfile $file --output-files-dir $SQL_FILES_STEP_DIR
  done

  if [ -f $SQL_FILES_STEP_DIR/ts"${STEP}".sql ]; then echoit "Removing existing ts"${STEP}".sql file from ${SQL_FILES_STEP_DIR}"; rm $SQL_FILES_STEP_DIR/ts"${STEP}".sql; fi

  touch $SQL_FILES_STEP_DIR/ts"${STEP}".sql

  ${BASEDIR}/bin/mysql -uroot -S${SOCKET} -e "select TABLESPACE_NAME from INFORMATION_SCHEMA.FILES WHERE TABLESPACE_NAME LIKE 'tab%'" | while read TS_NAME  ; do
    if [[ $TS_NAME =~ TABLESPACE_NAME ]]; then continue; fi
    if [[ $TS_NAME =~ (_e)  ]]; then
      ENCRYPTION=Y
    else
      ENCRYPTION=N; fi

    if [[ $TS_NAME =~ ([0-9]+k) ]]; then FILE_BLOCK_SIZE=${BASH_REMATCH[1]}; else FILE_BLOCK_SIZE=16k; fi

    echo "CREATE TABLESPACE $TS_NAME FILE_BLOCK_SIZE=$FILE_BLOCK_SIZE ENCRYPTION='$ENCRYPTION';" >> $SQL_FILES_STEP_DIR/ts"${STEP}".sql
    done

  if [ ${PXC} -eq 1 ]; then if ! ${BASEDIR}/bin/mysql -uroot -S"${SOCKET}" -e"set global pxc_strict_mode=DISABLED"; then
      echoit "ERROR: Failed to set pxc_strict_mode to DISABLED"
      return 1
    fi
  fi

  if [ -f $MYEXTRA_FILE ]; then cp "$MYEXTRA_FILE" "$SQL_FILES_STEP_DIR"; fi
  echo ###### Taking dump ######
  if ! ${BASEDIR}/bin/mysqldump -uroot -S ${SOCKET} --databases test --set-gtid-purged=OFF > ${SQL_FILES_STEP_DIR}/dump_pstress"${STEP}".sql; then
    echoit "ERROR: Failed to take dump"
    return 1
  else
    echoit "Dump file created ${SQL_FILES_STEP_DIR}/dump_pstress"${STEP}".sql"
  fi

  if [ ${PXC} -eq 1 ]; then if ! ${BASEDIR}/bin/mysql -uroot -S"${SOCKET}" -e"set global pxc_strict_mode=DEFAULT"; then
      echoit "ERROR: Failed to set pxc_strict_mode to DEFAULT"
      return 1
    fi
  fi
}
# Repeat or resume step
function pstress_step() {
  if [ $REPEAT_MODE -eq 1 ]; then
    PREV_TRIAL=$[ ${STEP} - 1 ]
    TRIAL=$STEP
    TRIAL_DIR=${RESUME_INCIDENT_DIR}/${TRIAL}.$COUNT
  elif [ $RESUME_MODE -eq 1 ] || [ ${GET_DUMP_AND_SQL_FILES} -eq 1 ]; then
    PREV_TRIAL=$TRIAL
    TRIAL=$[ ${TRIAL} + 1 ]
    TRIAL_DIR=${RESUME_INCIDENT_DIR}/${TRIAL}
  fi
  PREV_TRIAL_DIR=${RESUME_INCIDENT_DIR}/${PREV_TRIAL}

  echoit "====== TRIAL #${TRIAL} ($COUNT) ======"
  echoit "Ensuring there are no relevant mysqld server running..."
  KILLPID=$(ps -ef | grep mysqld | grep -v grep | awk '{print $2}' | tr '\n' ' ')
  { kill -9 $KILLPID && wait $KILLPID; } 2>/dev/null
  if [ ${PXC} -eq 0 ]; then
    mkdir -p ${TRIAL_DIR}/data ${TRIAL_DIR}/tmp ${TRIAL_DIR}/log
    echoit "Copying datadir from previous trial ${PREV_TRIAL_DIR}/data into ${TRIAL_DIR}/data";
    rsync -ar --exclude='*core*' ${PREV_TRIAL_DIR}/data/ ${TRIAL_DIR}/data 2>&1
    if [ ${ENCRYPTION_RUN} -eq 1 -a ${COMPONENT_KEYRING_FILE} -eq 1 ]; then
      sed -i "s|$RUNDIR/$(($TRIAL-1))|$TRIAL_DIR|g" ${TRIAL_DIR}/data/component_keyring_file.cnf
    fi
  elif [ ${PXC} -eq 1 ]; then
    mkdir -p ${TRIAL_DIR}/tmp1 ${TRIAL_DIR}/tmp2 ${TRIAL_DIR}/tmp3
    mkdir ${TRIAL_DIR}/node1 ${TRIAL_DIR}/node2 ${TRIAL_DIR}/node3
    echoit "Copying datadir from ${PREV_TRIAL_DIR}/node1 into ${TRIAL_DIR}/node1";
    echoit "Copying datadir from ${PREV_TRIAL_DIR}/node2 into ${TRIAL_DIR}/node2";
    echoit "Copying datadir from ${PREV_TRIAL_DIR}/node3 into ${TRIAL_DIR}/node3";
    rsync -ar --exclude='*core*' ${PREV_TRIAL_DIR}/node1/ ${TRIAL_DIR}/node1 2>&1
    rsync -ar --exclude='*core*' ${PREV_TRIAL_DIR}/node2/ ${TRIAL_DIR}/node2 2>&1
    rsync -ar --exclude='*core*' ${PREV_TRIAL_DIR}/node3/ ${TRIAL_DIR}/node3 2>&1
    echoit "Copying config file from ${INCIDENT_DIR}/${TRIAL}/n1.cnf into ${TRIAL_DIR}/n1.cnf"
    echoit "Copying config file from ${INCIDENT_DIR}/${TRIAL}/n2.cnf into ${TRIAL_DIR}/n2.cnf"
    echoit "Copying config file from ${INCIDENT_DIR}/${TRIAL}/n3.cnf into ${TRIAL_DIR}/n3.cnf"
    cp ${INCIDENT_DIR}/${TRIAL}/n1.cnf ${TRIAL_DIR}/n1.cnf
    cp ${INCIDENT_DIR}/${TRIAL}/n2.cnf ${TRIAL_DIR}/n2.cnf
    cp ${INCIDENT_DIR}/${TRIAL}/n3.cnf ${TRIAL_DIR}/n3.cnf

    sed -i "s|$RUNDIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n1.cnf
    sed -i "s|$RUNDIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n2.cnf
    sed -i "s|$RUNDIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n3.cnf

    sed -i "s|$INCIDENT_DIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n1.cnf
    sed -i "s|$INCIDENT_DIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n2.cnf
    sed -i "s|$INCIDENT_DIR/$TRIAL|$TRIAL_DIR|g" ${TRIAL_DIR}/n3.cnf

    sed -i 's|safe_to_bootstrap:.*$|safe_to_bootstrap: 1|' ${TRIAL_DIR}/node1/grastate.dat

    if [ ${ENCRYPTION_RUN} -eq 1 -a ${COMPONENT_KEYRING_FILE} -eq 1 ]; then
      sed -i "s|$RUNDIR/${PREV_TRIAL}|$TRIAL_DIR|g" ${TRIAL_DIR}/node1/component_keyring_file.cnf
      sed -i "s|$RUNDIR/${PREV_TRIAL}|$TRIAL_DIR|g" ${TRIAL_DIR}/node2/component_keyring_file.cnf
      sed -i "s|$RUNDIR/${PREV_TRIAL}|$TRIAL_DIR|g" ${TRIAL_DIR}/node3/component_keyring_file.cnf
    fi
  fi

# Start server
  if [ ${PXC} -eq 0 ]; then
    SOCKET=${TRIAL_DIR}/socket.sock
    DATADIR=${TRIAL_DIR}/data
    TEMPDIR=${TRIAL_DIR}/tmp
    ERROR=${TRIAL_DIR}/log/master.err
    PID_FILE=${TRIAL_DIR}/pid.pid
    start_server
  elif [ $PXC -eq 1 ]; then
    SOCKET1=${TRIAL_DIR}/node1/node1_socket.sock
    SOCKET2=${TRIAL_DIR}/node2/node2_socket.sock
    SOCKET3=${TRIAL_DIR}/node3/node3_socket.sock
    CONFIG1=${TRIAL_DIR}/n1.cnf
    CONFIG2=${TRIAL_DIR}/n2.cnf
    CONFIG3=${TRIAL_DIR}/n3.cnf
    ERR_FILE1=${TRIAL_DIR}/node1/node1.err
    ERR_FILE2=${TRIAL_DIR}/node2/node2.err
    ERR_FILE3=${TRIAL_DIR}/node3/node3.err
    start_pxc_server
  fi

  if [ ${GET_DUMP_AND_SQL_FILES} -eq 1 ]; then
    echoit "Get dump and sql files for the step"
    get_dump_and_sql_files

    if [ ${KEEP_SERVER_RUNNING:-0} -eq 1 ]; then
      echoit "Skipping killing the server and exiting"
      exit 0
    fi

  else
    # Start pstress
    LOGDIR=${TRIAL_DIR}
    METADATA_PATH=${RESUME_INCIDENT_DIR}
    start_pstress
    echoit "pstress run details:$(grep -i 'SUMMARY.*queries failed' ${TRIAL_DIR}/*.sql ${TRIAL_DIR}/*.log | sed 's|.*:||')"
  fi

# Terminate mysqld
  kill_server $SIGNAL
  sleep 5 #^ Ensure the mysqld is gone completely
  if [ $(ls -l ${TRIAL_DIR}/*/*core* 2>/dev/null | wc -l) -ge 1 ]; then
    echoit "mysqld coredump detected at $(ls ${TRIAL_DIR}/*/*core* 2>/dev/null)"
    echoit "Bug found (as per error log): $(${SCRIPT_PWD}/search_string.sh ${TRIAL_DIR}/log/master.err)"
  fi
}

# Start pstress on running server
function start_pstress() {
  echoit "Starting pstress run for step:${TRIAL} ..."
  if [ ${PXC} -eq 1 ]; then
    SOCKET=${SOCKET1}
  fi
  CMD="${PSTRESS_BIN} --database=test --threads=${THREADS} --queries-per-thread=${QUERIES_PER_THREAD} --logdir=${LOGDIR} --user=root --socket=$SOCKET --seed ${SEED} --step ${TRIAL} --metadata-path ${METADATA_PATH}/ --seconds ${PSTRESS_RUN_TIMEOUT} ${DYNAMIC_QUERY_PARAMETER} --engine=${ENGINE}"
  echoit "$CMD"
  $CMD > ${LOGDIR}/pstress.log 2>&1 &
  PSPID="$!"

  echoit "pstress running (Max duration: ${PSTRESS_RUN_TIMEOUT}s)..."
  for X in $(seq 1 ${PSTRESS_RUN_TIMEOUT}); do
    sleep 1
    if [ "`ps -ef | grep $PSPID | grep -v grep`" == "" ]; then  # pstress ended
      break
    fi
    if [ $X -ge ${PSTRESS_RUN_TIMEOUT} ]; then
      echoit "${PSTRESS_RUN_TIMEOUT}s timeout reached. Terminating this trial..."
      if [ ${TIMEOUT_INCREMENT} != 0 ]; then
        echoit "TIMEOUT_INCREMENT option was enabled and set to ${TIMEOUT_INCREMENT} sec"
        echoit "${TIMEOUT_INCREMENT}s will be added to the next trial timeout."
      else
        echoit "TIMEOUT_INCREMENT option was disabled and set to 0"
      fi
      PSTRESS_RUN_TIMEOUT=$[ ${PSTRESS_RUN_TIMEOUT} + ${TIMEOUT_INCREMENT} ]
      break
    fi
  done
}

function pxc_startup_status() {
  SOCKET=$1
  ERR_FILE=$2
  for X in $(seq 0 ${PXC_START_TIMEOUT}); do
    sleep 1
    if ${BASEDIR}/bin/mysqladmin -uroot -S${SOCKET} ping > /dev/null 2>&1; then
      break
    fi
    if [ $X -eq ${PXC_START_TIMEOUT} ]; then
      if [ ${RESUME_MODE} -eq 1 ]; then
        echo "Could not start the server. Check error logs: ${ERR_FILE}"
      else
        echo "Could not start the server. Check error logs: ${ERR_FILE}"
      fi
      exit 1
    fi
  done
}

parse_args $*
if [ $# -eq 0 ]; then
  Help
  exit 1
fi

if [ "${RESUME_DIR}" == "" ]; then
  Help
  exit 1
elif [ "${INCIDENT_DIR}" == "" ]; then
  Help
  exit 1
elif [ "${STEP}" == "" ]; then
  Help
  exit 1
fi

if [[ ${REPEAT_MODE} -eq 1 || ${GET_DUMP_AND_SQL_FILES} -eq 1 || ${GET_SINGLE_THREADED_PSTRESS_SQL_FILES} -eq 1 ]]; then
  RESUME_MODE=0
fi

# Check that only one of --repeat, --get-dump-and-sql-files, or --get-single-threaded-pstress-sql-files is provided
OPTION_COUNT=0
if [ ${REPEAT_MODE:-0} -eq 1 ]; then
  OPTION_COUNT=$((OPTION_COUNT + 1))
fi
if [ ${GET_DUMP_AND_SQL_FILES:-0} -eq 1 ]; then
  OPTION_COUNT=$((OPTION_COUNT + 1))
fi
if [ ${GET_SINGLE_THREADED_PSTRESS_SQL_FILES:-0} -eq 1 ]; then
  OPTION_COUNT=$((OPTION_COUNT + 1))
fi

if [ ${OPTION_COUNT} -gt 1 ]; then
  echoit "ERROR: Only one of --repeat, --get-dump-and-sql-files, or --get-single-threaded-pstress-sql-files can be specified"
  echoit "Please use only one of these options at a time"
  exit 1
fi

# Check that --sql-files-dir is only used with --get-single-threaded-pstress-sql-files or --get-dump-and-sql-files
if [ -n "${SQL_FILES_DIR}" ]; then
  if [ ${GET_DUMP_AND_SQL_FILES} -ne 1 ] && [ ${GET_SINGLE_THREADED_PSTRESS_SQL_FILES} -ne 1 ]; then
    echoit "WARNING: --sql-files-dir is only valid with --get-single-threaded-pstress-sql-files or --get-dump-and-sql-files"
    echoit "WARNING: The --sql-files-dir option will be ignored in the current mode"
  fi
fi

# Additional checks
# 1. Check if provided incident directory exists
# 2. Check if provided resume directory exists
if [ ! -d ${INCIDENT_DIR} ]; then
  echo "${INCIDENT_DIR} path does not exist"
  exit 1
elif [ ! -d ${RESUME_DIR} ]; then
  echo "${RESUME_DIR} path does not exist"
  exit 1
fi

if [ ${REPEAT_MODE} -eq 1 ]; then
  echoit "Running pstress in repeat mode"
  RESUME_MODE=0
elif [[ ${GET_DUMP_AND_SQL_FILES} -eq 1 || ${GET_SINGLE_THREADED_PSTRESS_SQL_FILES} -eq 1 ]]; then
  if [ -z "$SQL_FILES_DIR" ]; then
    SQL_FILES_DIR=${HOME}/pstress_sql_files
  fi
  SQL_FILES_STEP_DIR=${SQL_FILES_DIR}/${STEP}
  if [ ! -d $SQL_FILES_STEP_DIR ]; then
    echoit "Directory '$SQL_FILES_STEP_DIR' does not exist. Creating now..."
    mkdir -p $SQL_FILES_STEP_DIR
  else
    echoit "SQL files directory '$SQL_FILES_STEP_DIR' already exists, will override the existing files"
  fi
  if [ ${GET_SINGLE_THREADED_PSTRESS_SQL_FILES:-0} -eq 1 ]; then
    echoit "Fetching the single threaded pstress sql files until the step:${STEP} and exiting"
    for step in $(seq 1 $STEP); do
      for file in ${INCIDENT_DIR}/${step}/default.node.tld_step_${step}*
      do
        ${SCRIPT_PWD}/pstress_log_to_sql_converter.sh --logfile $file --output-files-dir $SQL_FILES_STEP_DIR
      done
    done
    exit 0
  fi
  RESUME_MODE=0
  REPEAT_MODE=0
elif [ ${RESUME_MODE} -eq 1 ]; then
  echoit "Running pstress in resume mode"
else
  echoit "Invalid option(s) passed. Terminating..."
  exit 1
fi

CONFIGURATION_FILE=$(find ${INCIDENT_DIR} -name '*.conf' | xargs readlink -f)
if [[ ${CONFIGURATION_FILE} =~ "pstress-run-PXC" ]]; then PXC=1; fi
source ${CONFIGURATION_FILE}
RUNDIR=$(cat ${INCIDENT_DIR}/pstress-run.log | grep "Rundir:" | grep -oP '(?<=Rundir: )[^ ]*')
if [ -f ${INCIDENT_DIR}/seed ]; then
  SEED=$(cat ${INCIDENT_DIR}/seed)
else
  echo "Unable to find seed file in the ${INCIDENT_DIR}"
  echo "Make sure to use the parent incident directory generated by pstress"
  exit 1
fi

if [ ${ENGINE} == "RocksDB" ]; then
  ENCRYPTION_RUN=0
fi

if [ ${ENCRYPTION_RUN} -eq 0 ]; then
 PLUGIN_KEYRING_FILE=0
 COMPONENT_KEYRING_FILE=0
fi

if [ ${PXC} -eq 1 ]; then
  DYNAMIC_QUERY_PARAMETER="$DYNAMIC_QUERY_PARAMETER --pk-prob 100 --alt-discard-tbs 0"
  if [ ${ENCRYPTION_RUN} -eq 1 ]; then
    if [ ${PLUGIN_KEYRING_FILE} -eq 1 ]; then
      KEYRING_PARAM="--early-plugin-load=keyring_file.so --keyring_file_data=keyring"
    fi
  elif [ ${ENCRYPTION_RUN} -eq 0 ]; then
     DYNAMIC_QUERY_PARAMETER="$DYNAMIC_QUERY_PARAMETER --no-encryption"
  fi
  if [ ${GCACHE_ENCRYPTION} -eq 0 ]; then
    DYNAMIC_QUERY_PARAMETER="$DYNAMIC_QUERY_PARAMETER --rotate-gcache-key 0"
  fi
elif [ ${PXC} -eq 0 ]; then
  if [ ${ENCRYPTION_RUN} -eq 1 ]; then
    if [ ${PLUGIN_KEYRING_FILE} -eq 1 ]; then
      KEYRING_PARAM="--early-plugin-load=keyring_file.so --keyring_file_data=keyring"
    fi
  elif [ ${ENCRYPTION_RUN} -eq 0 ]; then
    DYNAMIC_QUERY_PARAMETER="$DYNAMIC_QUERY_PARAMETER --no-encryption"
  fi
fi

# Find mysqld binary
if [ -r ${INCIDENT_DIR}/mysqld/bin/mysqld ]; then
  BIN=${INCIDENT_DIR}/mysqld/bin/mysqld
else
  echoit "Assert: there is no (script readable) mysqld binary at ${INCIDENT_DIR}/bin/mysqld ?"
  exit 1
fi

MYEXTRA_FILE=${INCIDENT_DIR}/${STEP}/MYEXTRA
if [ -f "$MYEXTRA_FILE" ]; then
  LINE_COUNT=$(wc -l < "$MYEXTRA_FILE" | tr -d ' ')
  if [ "$LINE_COUNT" -ne 1 ]; then
    echoit "Error: $MYEXTRA_FILE must contain exactly one line, but it has $LINE_COUNT line(s)"
    exit 1
  fi
  IFS= read -r MYEXTRA < "$MYEXTRA_FILE"
  echoit "options used for server ${MYEXTRA}"
else
  echoit "No MYEXTRA file found. Using default options"
  MYEXTRA=""
fi

rm -rf ${RESUME_DIR}/${RANDOMD}
RESUME_INCIDENT_DIR=${RESUME_DIR}/${RANDOMD}

if [ ${PXC} -eq 1 ]; then
  mkdir -p ${RESUME_INCIDENT_DIR}/cert
  cp ${INCIDENT_DIR}/node1.template/*.pem ${RESUME_INCIDENT_DIR}/cert/
fi

if [ ${RESUME_MODE} -eq 1 ]; then
  echoit "Resuming pstress iterations from step:${STEP}"
elif [ ${REPEAT_MODE} -eq 1 ]; then
  echoit "Repeating step ${STEP} (${REPEAT}) number of times"
elif [ ${GET_DUMP_AND_SQL_FILES} -eq 1 ]; then
  echoit "Triggering the run to get the dump file for the step:${STEP}"
fi

TRIAL=$[ ${STEP} - 1 ]
if [ ${STEP} -gt 1 ]; then
  echoit "Generating new trial workdir ${RESUME_INCIDENT_DIR}/${TRIAL}"
  mkdir -p ${RESUME_INCIDENT_DIR}/${TRIAL}
  if [ ${PXC} -eq 0 ]; then
    echo "Taking backup of datadir from ${INCIDENT_DIR}/${TRIAL}/data into ${RESUME_INCIDENT_DIR}/${TRIAL}/"
    rsync -ar --exclude='*core*' ${INCIDENT_DIR}/${TRIAL}/data/ ${RESUME_INCIDENT_DIR}/${TRIAL}/data 2>&1
  elif [ ${PXC} -eq 1 ]; then
    echo "Taking backup of datadir from ${INCIDENT_DIR}/${TRIAL}/node1 into ${RESUME_INCIDENT_DIR}/${TRIAL}/"
    echo "Taking backup of datadir from ${INCIDENT_DIR}/${TRIAL}/node2 into ${RESUME_INCIDENT_DIR}/${TRIAL}/"
    echo "Taking backup of datadir from ${INCIDENT_DIR}/${TRIAL}/node3 into ${RESUME_INCIDENT_DIR}/${TRIAL}/"
    rsync -ar --exclude='*core*' ${INCIDENT_DIR}/${TRIAL}/node1/ ${RESUME_INCIDENT_DIR}/${TRIAL}/node1 2>&1
    rsync -ar --exclude='*core*' ${INCIDENT_DIR}/${TRIAL}/node2/ ${RESUME_INCIDENT_DIR}/${TRIAL}/node2 2>&1
    rsync -ar --exclude='*core*' ${INCIDENT_DIR}/${TRIAL}/node3/ ${RESUME_INCIDENT_DIR}/${TRIAL}/node3 2>&1
  fi
  if [ -f ${INCIDENT_DIR}/step_${TRIAL}.dll ]; then
    echo "Copying step_${TRIAL}.dll file into ${RESUME_INCIDENT_DIR}"
    cp ${INCIDENT_DIR}/step_${TRIAL}.dll ${RESUME_INCIDENT_DIR}
  else
    echo "The step_${TRIAL}.dll file does not exist. Can not continue"
    exit 1
  fi
elif [ ${STEP} -eq 1 ]; then
  echo "If you intend to repeat or resume from step 1, execute pstress-run.sh or please perform a normal run using same seed number"
  exit 1
else
  echo "Invalid step provided. Exiting..."
  exit 1
fi

if [ ${RESUME_MODE} -eq 1 ]; then
  LEFT_TRIALS=$[ ${TRIALS} - ${TRIAL} ]
elif [ ${REPEAT_MODE} -eq 1 ]; then
  LEFT_TRIALS=${REPEAT}
elif [ ${GET_DUMP_AND_SQL_FILES} -eq 1 ]; then
  LEFT_TRIALS=1
fi

for COUNT in $(seq 1 ${LEFT_TRIALS}); do
    pstress_step
done

echoit "Done. Attempting to cleanup the pstress rundir ${RUNDIR}..."
rm -rf ${RUNDIR}
echoit "The results of this run can be found in the repeat/resume dir ${RESUME_DIR}..."
echoit "Done. Exiting $0 with exit code 0..."
exit 0
