SELECT count(*) FROM T1 JOIN T2 ON T1_INT_1 = T2_INT_1 ORDER BY T2_VARCHAR_1 DESC, T1_VARCHAR_1 
SELECT count(*) FROM T1
SELECT sum(T1_INT_1) FROM T1
SELECT avg(T1_INT_1) FROM T1
SELECT max(T1_INT_1) FROM T1
SELECT min(T1_INT_1) FROM T1
SELECT * FROM T1
SELECT DATE_ADD(T1_DATE_1, INTERVAL 1 DAY) FROM T1
SELECT DATE_SUB(T1_DATE_1, INTERVAL 1 DAY) FROM T1
